sudo: required
dist: trusty

language: ruby

service:
  - docker

install:
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker-compose up --build -d
  - sleep 20
  - docker-compose run -e "RAILS_ENV=test" web rake db:create db:migrate
  - sleep 5
  - docker-compose run web yarn

script:
  - docker-compose run web rspec spec
  - docker-compose run web yarn test __tests__

after_script:
  - docker-compose down