sudo: required
dist: trusty

language: ruby

service:
  - docker

install:
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose run -e web bin/rake db:create db:migrate

script:
  - docker-compose run web rspec spec

after_script:
  - docker-compose down