#!/bin/bash
set -e

if [ -f /mik-system/tmp/pids/server.pid ]; then
  rm /mik-system/tmp/pids/server.pid
fi

bundle exec rake db:create
bundle exec rake db:migrate

bundle exec rails s -p 3000 -b '0.0.0.0'

exec "\$@"