version: '3'
services:
  db:
    build:
      context: .
      dockerfile: containers/production/database/Dockerfile
    image: production-db
    ports:
      - 5432:5432
    env_file:
      - containers/production/.env
    volumes:
      - data:/var/lib/postgresql/db-data
  web:
    build:
      context: .
      dockerfile: containers/production/Dockerfile
    image: owlaukka/mik-system
    env_file:
      - containers/production/.env
    command: containers/scripts/wait-for-it.sh db:5432 -- containers/production/entrypoint
    volumes:
      - assets:/mik-system/public/assets
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  assets:
    external: false
  data:
    external: false