#!/bin/bash
set -e

if [[ -a /tmp/puma.pid ]]; then
  rm /tmp/puma.pid
fi

bundle exec rake db:create
bundle exec rake db:migrate

if [[ $RAILS_ENV == "production" ]]; then
  rake assets:precompile
fi

bundle exec rails s -p 3000 -b '0.0.0.0'

exec "\$@"